---
- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.5/prometheus-2.45.5.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/prometheus-2.45.5.linux-amd64/prometheus

- name: Create Prometheus configuration
  copy:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'app_server'
          static_configs:
            - targets: ['172.31.5.28:9100']
    dest: /opt/prometheus-2.45.5.linux-amd64/prometheus.yml

- name: create group
  group:
    name: prometheus
    system: yes
  
- name: create user
  user:
    name: prometheus
    group: prometheus
    system: yes
    shell: /sbin/nologin

- name: make folders
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0775
  loop:
    - /var/lib/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/rules.s
    - /etc/prometheus/files_sd

- name: Move file
  command: mv /opt/prometheus-2.45.5.linux-amd64/prometheus /opt/prometheus-2.45.5.linux-amd64/promtool /usr/local/sbin/

- name: Move file
  command: mv /opt/prometheus-2.45.5.linux-amd64/prometheus.yml /etc/prometheus/

- name: Create Prometheus service
  copy:
    content: |
      [Unit]
      Description=Prometheus
      Documentation=https://prometheus.io/docs/introduction/overview/
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      User=prometheus
      Group=prometheus
      ExecReload=/bin/kill -HUP $MAINPID
      ExecStart=/usr/local/sbin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries \
        --web.listen-address=0.0.0.0:9090 \
        --web.external-url=

      SyslogIdentifier=prometheus
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes