---
- name: Download app
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.32/etcd-v3.4.32-linux-amd64.tar.gz
    dest: /tmp/etcd.tar.gz

- name: Extract app
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/etcd-v3.4.32-linux-amd64/etcd

# - name: create group
#   group:
#     name: prometheus
#     system: yes
  
# - name: create user
#   user:
#     name: prometheus
#     group: prometheus
#     system: yes
#     shell: /sbin/nologin

# - name: make folders
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: prometheus
#     group: prometheus
#     mode: 0775
#   loop:
#     - /var/lib/node

- name: Move file
  command: mv "/opt/etcd-v3.4.32-linux-amd64/{{ item }}" /usr/local/sbin/
  loop:
    - etcd
    - etcdctl

# - name: Create Node Exporter service
#   copy:
#     content: |
#       [Unit]
#       Description=Prometheus Node Exporter
#       Documentation=https://prometheus.io/docs/introduction/overview/
#       Wants=network-online.target
#       After=network-online.target

#       [Service]
#       Type=simple
#       User=prometheus
#       Group=prometheus
#       ExecReload=/bin/kill -HUP $MAINPID
#       ExecStart=/var/lib/node/node_exporter

#       SyslogIdentifier=prometheus_node_exporter
#       Restart=always

#       [Install]
#       WantedBy=multi-user.target
#     dest: /etc/systemd/system/node.service

# - name: Start Node Exporter service
#   systemd:
#     name: node
#     state: started
#     enabled: yes